// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: plan.proto

package plan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// shared
type SuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	mi := &file_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{0}
}

func (x *SuccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// pin
type CreatePinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Expense       []*Expenses            `protobuf:"bytes,3,rep,name=expense,proto3" json:"expense,omitempty"`
	Location      float32                `protobuf:"fixed32,4,opt,name=location,proto3" json:"location,omitempty"`
	Parents       []string               `protobuf:"bytes,5,rep,name=parents,proto3" json:"parents,omitempty"`
	Participant   []string               `protobuf:"bytes,6,rep,name=participant,proto3" json:"participant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePinRequest) Reset() {
	*x = CreatePinRequest{}
	mi := &file_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePinRequest) ProtoMessage() {}

func (x *CreatePinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePinRequest.ProtoReflect.Descriptor instead.
func (*CreatePinRequest) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePinRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePinRequest) GetExpense() []*Expenses {
	if x != nil {
		return x.Expense
	}
	return nil
}

func (x *CreatePinRequest) GetLocation() float32 {
	if x != nil {
		return x.Location
	}
	return 0
}

func (x *CreatePinRequest) GetParents() []string {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *CreatePinRequest) GetParticipant() []string {
	if x != nil {
		return x.Participant
	}
	return nil
}

type CreatePinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PinId         string                 `protobuf:"bytes,2,opt,name=pinId,proto3" json:"pinId,omitempty"` //objectId AS a string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePinResponse) Reset() {
	*x = CreatePinResponse{}
	mi := &file_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePinResponse) ProtoMessage() {}

func (x *CreatePinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePinResponse.ProtoReflect.Descriptor instead.
func (*CreatePinResponse) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreatePinResponse) GetPinId() string {
	if x != nil {
		return x.PinId
	}
	return ""
}

type PinIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PinId         string                 `protobuf:"bytes,1,opt,name=pinId,proto3" json:"pinId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinIDRequest) Reset() {
	*x = PinIDRequest{}
	mi := &file_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinIDRequest) ProtoMessage() {}

func (x *PinIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinIDRequest.ProtoReflect.Descriptor instead.
func (*PinIDRequest) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{3}
}

func (x *PinIDRequest) GetPinId() string {
	if x != nil {
		return x.PinId
	}
	return ""
}

type GetPinByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         []byte                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Expense       []*Expenses            `protobuf:"bytes,5,rep,name=expense,proto3" json:"expense,omitempty"`
	Location      float32                `protobuf:"fixed32,6,opt,name=location,proto3" json:"location,omitempty"`
	Parents       []string               `protobuf:"bytes,7,rep,name=parents,proto3" json:"parents,omitempty"`
	Participant   []string               `protobuf:"bytes,8,rep,name=participant,proto3" json:"participant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPinByIDResponse) Reset() {
	*x = GetPinByIDResponse{}
	mi := &file_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPinByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPinByIDResponse) ProtoMessage() {}

func (x *GetPinByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPinByIDResponse.ProtoReflect.Descriptor instead.
func (*GetPinByIDResponse) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{4}
}

func (x *GetPinByIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPinByIDResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPinByIDResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *GetPinByIDResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetPinByIDResponse) GetExpense() []*Expenses {
	if x != nil {
		return x.Expense
	}
	return nil
}

func (x *GetPinByIDResponse) GetLocation() float32 {
	if x != nil {
		return x.Location
	}
	return 0
}

func (x *GetPinByIDResponse) GetParents() []string {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *GetPinByIDResponse) GetParticipant() []string {
	if x != nil {
		return x.Participant
	}
	return nil
}

type GetPinByParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPinByParticipantRequest) Reset() {
	*x = GetPinByParticipantRequest{}
	mi := &file_plan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPinByParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPinByParticipantRequest) ProtoMessage() {}

func (x *GetPinByParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPinByParticipantRequest.ProtoReflect.Descriptor instead.
func (*GetPinByParticipantRequest) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{5}
}

func (x *GetPinByParticipantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPinsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pins          []*GetPinResponse      `protobuf:"bytes,1,rep,name=pins,proto3" json:"pins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPinsResponse) Reset() {
	*x = GetPinsResponse{}
	mi := &file_plan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPinsResponse) ProtoMessage() {}

func (x *GetPinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPinsResponse.ProtoReflect.Descriptor instead.
func (*GetPinsResponse) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{6}
}

func (x *GetPinsResponse) GetPins() []*GetPinResponse {
	if x != nil {
		return x.Pins
	}
	return nil
}

type GetPinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PinId         string                 `protobuf:"bytes,1,opt,name=pinId,proto3" json:"pinId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         []byte                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Parents       []string               `protobuf:"bytes,4,rep,name=parents,proto3" json:"parents,omitempty"`
	Participant   []string               `protobuf:"bytes,5,rep,name=participant,proto3" json:"participant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPinResponse) Reset() {
	*x = GetPinResponse{}
	mi := &file_plan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPinResponse) ProtoMessage() {}

func (x *GetPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPinResponse.ProtoReflect.Descriptor instead.
func (*GetPinResponse) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{7}
}

func (x *GetPinResponse) GetPinId() string {
	if x != nil {
		return x.PinId
	}
	return ""
}

func (x *GetPinResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPinResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *GetPinResponse) GetParents() []string {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *GetPinResponse) GetParticipant() []string {
	if x != nil {
		return x.Participant
	}
	return nil
}

type UpdatePinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Expense       []*Expenses            `protobuf:"bytes,4,rep,name=expense,proto3" json:"expense,omitempty"`
	Location      float32                `protobuf:"fixed32,5,opt,name=location,proto3" json:"location,omitempty"`
	Parents       []string               `protobuf:"bytes,6,rep,name=parents,proto3" json:"parents,omitempty"`
	Participant   []string               `protobuf:"bytes,7,rep,name=participant,proto3" json:"participant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePinRequest) Reset() {
	*x = UpdatePinRequest{}
	mi := &file_plan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePinRequest) ProtoMessage() {}

func (x *UpdatePinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePinRequest.ProtoReflect.Descriptor instead.
func (*UpdatePinRequest) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePinRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePinRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePinRequest) GetExpense() []*Expenses {
	if x != nil {
		return x.Expense
	}
	return nil
}

func (x *UpdatePinRequest) GetLocation() float32 {
	if x != nil {
		return x.Location
	}
	return 0
}

func (x *UpdatePinRequest) GetParents() []string {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *UpdatePinRequest) GetParticipant() []string {
	if x != nil {
		return x.Participant
	}
	return nil
}

type Expenses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Expense       float32                `protobuf:"fixed32,3,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expenses) Reset() {
	*x = Expenses{}
	mi := &file_plan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expenses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expenses) ProtoMessage() {}

func (x *Expenses) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expenses.ProtoReflect.Descriptor instead.
func (*Expenses) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{9}
}

func (x *Expenses) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Expenses) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Expenses) GetExpense() float32 {
	if x != nil {
		return x.Expense
	}
	return 0
}

type UpdatePinImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image         []byte                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePinImageRequest) Reset() {
	*x = UpdatePinImageRequest{}
	mi := &file_plan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePinImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePinImageRequest) ProtoMessage() {}

func (x *UpdatePinImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePinImageRequest.ProtoReflect.Descriptor instead.
func (*UpdatePinImageRequest) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePinImageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePinImageRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

// whiteboard
type CreateWhiteboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pin           string                 `protobuf:"bytes,1,opt,name=pin,proto3" json:"pin,omitempty"`
	Day           int32                  `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWhiteboardRequest) Reset() {
	*x = CreateWhiteboardRequest{}
	mi := &file_plan_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWhiteboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWhiteboardRequest) ProtoMessage() {}

func (x *CreateWhiteboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWhiteboardRequest.ProtoReflect.Descriptor instead.
func (*CreateWhiteboardRequest) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{11}
}

func (x *CreateWhiteboardRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *CreateWhiteboardRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type CreateWhiteboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	WhiteboardId  string                 `protobuf:"bytes,2,opt,name=whiteboardId,proto3" json:"whiteboardId,omitempty"` //objectId AS a string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWhiteboardResponse) Reset() {
	*x = CreateWhiteboardResponse{}
	mi := &file_plan_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWhiteboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWhiteboardResponse) ProtoMessage() {}

func (x *CreateWhiteboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWhiteboardResponse.ProtoReflect.Descriptor instead.
func (*CreateWhiteboardResponse) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{12}
}

func (x *CreateWhiteboardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateWhiteboardResponse) GetWhiteboardId() string {
	if x != nil {
		return x.WhiteboardId
	}
	return ""
}

type WhiteboardIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WhiteboardId  string                 `protobuf:"bytes,1,opt,name=whiteboardId,proto3" json:"whiteboardId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhiteboardIDRequest) Reset() {
	*x = WhiteboardIDRequest{}
	mi := &file_plan_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhiteboardIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhiteboardIDRequest) ProtoMessage() {}

func (x *WhiteboardIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhiteboardIDRequest.ProtoReflect.Descriptor instead.
func (*WhiteboardIDRequest) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{13}
}

func (x *WhiteboardIDRequest) GetWhiteboardId() string {
	if x != nil {
		return x.WhiteboardId
	}
	return ""
}

type GetWhiteboardByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Pins          []string               `protobuf:"bytes,2,rep,name=pins,proto3" json:"pins,omitempty"`
	Day           int32                  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWhiteboardByIDResponse) Reset() {
	*x = GetWhiteboardByIDResponse{}
	mi := &file_plan_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWhiteboardByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWhiteboardByIDResponse) ProtoMessage() {}

func (x *GetWhiteboardByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWhiteboardByIDResponse.ProtoReflect.Descriptor instead.
func (*GetWhiteboardByIDResponse) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{14}
}

func (x *GetWhiteboardByIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetWhiteboardByIDResponse) GetPins() []string {
	if x != nil {
		return x.Pins
	}
	return nil
}

func (x *GetWhiteboardByIDResponse) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type UpdateWhiteboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pins          []string               `protobuf:"bytes,2,rep,name=pins,proto3" json:"pins,omitempty"`
	PinChangeType string                 `protobuf:"bytes,3,opt,name=pinChangeType,proto3" json:"pinChangeType,omitempty"`
	Day           int32                  `protobuf:"varint,4,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWhiteboardRequest) Reset() {
	*x = UpdateWhiteboardRequest{}
	mi := &file_plan_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWhiteboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWhiteboardRequest) ProtoMessage() {}

func (x *UpdateWhiteboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWhiteboardRequest.ProtoReflect.Descriptor instead.
func (*UpdateWhiteboardRequest) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateWhiteboardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWhiteboardRequest) GetPins() []string {
	if x != nil {
		return x.Pins
	}
	return nil
}

func (x *UpdateWhiteboardRequest) GetPinChangeType() string {
	if x != nil {
		return x.PinChangeType
	}
	return ""
}

func (x *UpdateWhiteboardRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

var File_plan_proto protoreflect.FileDescriptor

const file_plan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"plan.proto\x12\x04plan\"+\n" +
	"\x0fSuccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xca\x01\n" +
	"\x10CreatePinRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12(\n" +
	"\aexpense\x18\x03 \x03(\v2\x0e.plan.ExpensesR\aexpense\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\x02R\blocation\x12\x18\n" +
	"\aparents\x18\x05 \x03(\tR\aparents\x12 \n" +
	"\vparticipant\x18\x06 \x03(\tR\vparticipant\"C\n" +
	"\x11CreatePinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05pinId\x18\x02 \x01(\tR\x05pinId\"$\n" +
	"\fPinIDRequest\x12\x14\n" +
	"\x05pinId\x18\x01 \x01(\tR\x05pinId\"\xfc\x01\n" +
	"\x12GetPinByIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\fR\x05image\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12(\n" +
	"\aexpense\x18\x05 \x03(\v2\x0e.plan.ExpensesR\aexpense\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\x02R\blocation\x12\x18\n" +
	"\aparents\x18\a \x03(\tR\aparents\x12 \n" +
	"\vparticipant\x18\b \x03(\tR\vparticipant\"4\n" +
	"\x1aGetPinByParticipantRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x0fGetPinsResponse\x12(\n" +
	"\x04pins\x18\x01 \x03(\v2\x14.plan.GetPinResponseR\x04pins\"\x8c\x01\n" +
	"\x0eGetPinResponse\x12\x14\n" +
	"\x05pinId\x18\x01 \x01(\tR\x05pinId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\fR\x05image\x12\x18\n" +
	"\aparents\x18\x04 \x03(\tR\aparents\x12 \n" +
	"\vparticipant\x18\x05 \x03(\tR\vparticipant\"\xda\x01\n" +
	"\x10UpdatePinRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12(\n" +
	"\aexpense\x18\x04 \x03(\v2\x0e.plan.ExpensesR\aexpense\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\x02R\blocation\x12\x18\n" +
	"\aparents\x18\x06 \x03(\tR\aparents\x12 \n" +
	"\vparticipant\x18\a \x03(\tR\vparticipant\"H\n" +
	"\bExpenses\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aexpense\x18\x03 \x01(\x02R\aexpense\"=\n" +
	"\x15UpdatePinImageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05image\x18\x02 \x01(\fR\x05image\"=\n" +
	"\x17CreateWhiteboardRequest\x12\x10\n" +
	"\x03pin\x18\x01 \x01(\tR\x03pin\x12\x10\n" +
	"\x03day\x18\x02 \x01(\x05R\x03day\"X\n" +
	"\x18CreateWhiteboardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\fwhiteboardId\x18\x02 \x01(\tR\fwhiteboardId\"9\n" +
	"\x13WhiteboardIDRequest\x12\"\n" +
	"\fwhiteboardId\x18\x01 \x01(\tR\fwhiteboardId\"[\n" +
	"\x19GetWhiteboardByIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04pins\x18\x02 \x03(\tR\x04pins\x12\x10\n" +
	"\x03day\x18\x03 \x01(\x05R\x03day\"u\n" +
	"\x17UpdateWhiteboardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04pins\x18\x02 \x03(\tR\x04pins\x12$\n" +
	"\rpinChangeType\x18\x03 \x01(\tR\rpinChangeType\x12\x10\n" +
	"\x03day\x18\x04 \x01(\x05R\x03day2\xce\x05\n" +
	"\fPlansService\x12<\n" +
	"\tCreatePin\x12\x16.plan.CreatePinRequest\x1a\x17.plan.CreatePinResponse\x12:\n" +
	"\n" +
	"GetPinByID\x12\x12.plan.PinIDRequest\x1a\x18.plan.GetPinByIDResponse\x12N\n" +
	"\x13GetPinByParticipant\x12 .plan.GetPinByParticipantRequest\x1a\x15.plan.GetPinsResponse\x12:\n" +
	"\tUpdatePin\x12\x16.plan.UpdatePinRequest\x1a\x15.plan.SuccessResponse\x12D\n" +
	"\x0eUpdatePinImage\x12\x1b.plan.UpdatePinImageRequest\x1a\x15.plan.SuccessResponse\x12:\n" +
	"\rDeletePinByID\x12\x12.plan.PinIDRequest\x1a\x15.plan.SuccessResponse\x12Q\n" +
	"\x10CreateWhiteboard\x12\x1d.plan.CreateWhiteboardRequest\x1a\x1e.plan.CreateWhiteboardResponse\x12O\n" +
	"\x11GetWhiteboardByID\x12\x19.plan.WhiteboardIDRequest\x1a\x1f.plan.GetWhiteboardByIDResponse\x12H\n" +
	"\x10UpdateWhiteboard\x12\x1d.plan.UpdateWhiteboardRequest\x1a\x15.plan.SuccessResponse\x12H\n" +
	"\x14DeleteWhiteboardByID\x12\x19.plan.WhiteboardIDRequest\x1a\x15.plan.SuccessResponseB\x13Z\x11shared/proto/planb\x06proto3"

var (
	file_plan_proto_rawDescOnce sync.Once
	file_plan_proto_rawDescData []byte
)

func file_plan_proto_rawDescGZIP() []byte {
	file_plan_proto_rawDescOnce.Do(func() {
		file_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plan_proto_rawDesc), len(file_plan_proto_rawDesc)))
	})
	return file_plan_proto_rawDescData
}

var file_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_plan_proto_goTypes = []any{
	(*SuccessResponse)(nil),            // 0: plan.SuccessResponse
	(*CreatePinRequest)(nil),           // 1: plan.CreatePinRequest
	(*CreatePinResponse)(nil),          // 2: plan.CreatePinResponse
	(*PinIDRequest)(nil),               // 3: plan.PinIDRequest
	(*GetPinByIDResponse)(nil),         // 4: plan.GetPinByIDResponse
	(*GetPinByParticipantRequest)(nil), // 5: plan.GetPinByParticipantRequest
	(*GetPinsResponse)(nil),            // 6: plan.GetPinsResponse
	(*GetPinResponse)(nil),             // 7: plan.GetPinResponse
	(*UpdatePinRequest)(nil),           // 8: plan.UpdatePinRequest
	(*Expenses)(nil),                   // 9: plan.Expenses
	(*UpdatePinImageRequest)(nil),      // 10: plan.UpdatePinImageRequest
	(*CreateWhiteboardRequest)(nil),    // 11: plan.CreateWhiteboardRequest
	(*CreateWhiteboardResponse)(nil),   // 12: plan.CreateWhiteboardResponse
	(*WhiteboardIDRequest)(nil),        // 13: plan.WhiteboardIDRequest
	(*GetWhiteboardByIDResponse)(nil),  // 14: plan.GetWhiteboardByIDResponse
	(*UpdateWhiteboardRequest)(nil),    // 15: plan.UpdateWhiteboardRequest
}
var file_plan_proto_depIdxs = []int32{
	9,  // 0: plan.CreatePinRequest.expense:type_name -> plan.Expenses
	9,  // 1: plan.GetPinByIDResponse.expense:type_name -> plan.Expenses
	7,  // 2: plan.GetPinsResponse.pins:type_name -> plan.GetPinResponse
	9,  // 3: plan.UpdatePinRequest.expense:type_name -> plan.Expenses
	1,  // 4: plan.PlansService.CreatePin:input_type -> plan.CreatePinRequest
	3,  // 5: plan.PlansService.GetPinByID:input_type -> plan.PinIDRequest
	5,  // 6: plan.PlansService.GetPinByParticipant:input_type -> plan.GetPinByParticipantRequest
	8,  // 7: plan.PlansService.UpdatePin:input_type -> plan.UpdatePinRequest
	10, // 8: plan.PlansService.UpdatePinImage:input_type -> plan.UpdatePinImageRequest
	3,  // 9: plan.PlansService.DeletePinByID:input_type -> plan.PinIDRequest
	11, // 10: plan.PlansService.CreateWhiteboard:input_type -> plan.CreateWhiteboardRequest
	13, // 11: plan.PlansService.GetWhiteboardByID:input_type -> plan.WhiteboardIDRequest
	15, // 12: plan.PlansService.UpdateWhiteboard:input_type -> plan.UpdateWhiteboardRequest
	13, // 13: plan.PlansService.DeleteWhiteboardByID:input_type -> plan.WhiteboardIDRequest
	2,  // 14: plan.PlansService.CreatePin:output_type -> plan.CreatePinResponse
	4,  // 15: plan.PlansService.GetPinByID:output_type -> plan.GetPinByIDResponse
	6,  // 16: plan.PlansService.GetPinByParticipant:output_type -> plan.GetPinsResponse
	0,  // 17: plan.PlansService.UpdatePin:output_type -> plan.SuccessResponse
	0,  // 18: plan.PlansService.UpdatePinImage:output_type -> plan.SuccessResponse
	0,  // 19: plan.PlansService.DeletePinByID:output_type -> plan.SuccessResponse
	12, // 20: plan.PlansService.CreateWhiteboard:output_type -> plan.CreateWhiteboardResponse
	14, // 21: plan.PlansService.GetWhiteboardByID:output_type -> plan.GetWhiteboardByIDResponse
	0,  // 22: plan.PlansService.UpdateWhiteboard:output_type -> plan.SuccessResponse
	0,  // 23: plan.PlansService.DeleteWhiteboardByID:output_type -> plan.SuccessResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_plan_proto_init() }
func file_plan_proto_init() {
	if File_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plan_proto_rawDesc), len(file_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plan_proto_goTypes,
		DependencyIndexes: file_plan_proto_depIdxs,
		MessageInfos:      file_plan_proto_msgTypes,
	}.Build()
	File_plan_proto = out.File
	file_plan_proto_goTypes = nil
	file_plan_proto_depIdxs = nil
}
