// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0--rc1
// source: plan.proto

package plan

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlansService_CreatePin_FullMethodName             = "/plan.PlansService/CreatePin"
	PlansService_GetPinByID_FullMethodName            = "/plan.PlansService/GetPinByID"
	PlansService_GetPinsByWhiteboard_FullMethodName   = "/plan.PlansService/GetPinsByWhiteboard"
	PlansService_GetPinByParticipant_FullMethodName   = "/plan.PlansService/GetPinByParticipant"
	PlansService_UpdatePin_FullMethodName             = "/plan.PlansService/UpdatePin"
	PlansService_UpdatePinImage_FullMethodName        = "/plan.PlansService/UpdatePinImage"
	PlansService_DeletePinByID_FullMethodName         = "/plan.PlansService/DeletePinByID"
	PlansService_DeletePinByWhiteboard_FullMethodName = "/plan.PlansService/DeletePinByWhiteboard"
	PlansService_CreateWhiteboard_FullMethodName      = "/plan.PlansService/CreateWhiteboard"
	PlansService_GetWhiteboardByID_FullMethodName     = "/plan.PlansService/GetWhiteboardByID"
	PlansService_UpdateWhiteboard_FullMethodName      = "/plan.PlansService/UpdateWhiteboard"
	PlansService_DeleteWhiteboardByID_FullMethodName  = "/plan.PlansService/DeleteWhiteboardByID"
	PlansService_CreateTrip_FullMethodName            = "/plan.PlansService/CreateTrip"
	PlansService_GetTripByID_FullMethodName           = "/plan.PlansService/GetTripByID"
	PlansService_UpdateTrip_FullMethodName            = "/plan.PlansService/UpdateTrip"
	PlansService_UpdateTripImage_FullMethodName       = "/plan.PlansService/UpdateTripImage"
	PlansService_DeleteTripByID_FullMethodName        = "/plan.PlansService/DeleteTripByID"
)

// PlansServiceClient is the client API for PlansService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlansServiceClient interface {
	// pin
	CreatePin(ctx context.Context, in *CreatePinRequest, opts ...grpc.CallOption) (*CreatePinResponse, error)
	GetPinByID(ctx context.Context, in *PinIDRequest, opts ...grpc.CallOption) (*GetPinByIDResponse, error)
	GetPinsByWhiteboard(ctx context.Context, in *ManyPinIDRequest, opts ...grpc.CallOption) (*GetPinsResponse, error)
	GetPinByParticipant(ctx context.Context, in *GetPinByParticipantRequest, opts ...grpc.CallOption) (*GetPinsResponse, error)
	UpdatePin(ctx context.Context, in *UpdatePinRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdatePinImage(ctx context.Context, in *UpdatePinImageRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	DeletePinByID(ctx context.Context, in *PinIDRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	DeletePinByWhiteboard(ctx context.Context, in *ManyPinIDRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	// whiteboard
	CreateWhiteboard(ctx context.Context, in *CreateWhiteboardRequest, opts ...grpc.CallOption) (*CreateWhiteboardResponse, error)
	GetWhiteboardByID(ctx context.Context, in *WhiteboardIDRequest, opts ...grpc.CallOption) (*GetWhiteboardByIDResponse, error)
	UpdateWhiteboard(ctx context.Context, in *UpdateWhiteboardRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	DeleteWhiteboardByID(ctx context.Context, in *WhiteboardIDRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	// trip
	CreateTrip(ctx context.Context, in *CreateTripRequest, opts ...grpc.CallOption) (*CreateTripResponse, error)
	GetTripByID(ctx context.Context, in *TripIDRequest, opts ...grpc.CallOption) (*GetTripByIDResponse, error)
	UpdateTrip(ctx context.Context, in *UpdateTripRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdateTripImage(ctx context.Context, in *UpdateTripImageRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	DeleteTripByID(ctx context.Context, in *TripIDRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
}

type plansServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlansServiceClient(cc grpc.ClientConnInterface) PlansServiceClient {
	return &plansServiceClient{cc}
}

func (c *plansServiceClient) CreatePin(ctx context.Context, in *CreatePinRequest, opts ...grpc.CallOption) (*CreatePinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePinResponse)
	err := c.cc.Invoke(ctx, PlansService_CreatePin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) GetPinByID(ctx context.Context, in *PinIDRequest, opts ...grpc.CallOption) (*GetPinByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPinByIDResponse)
	err := c.cc.Invoke(ctx, PlansService_GetPinByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) GetPinsByWhiteboard(ctx context.Context, in *ManyPinIDRequest, opts ...grpc.CallOption) (*GetPinsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPinsResponse)
	err := c.cc.Invoke(ctx, PlansService_GetPinsByWhiteboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) GetPinByParticipant(ctx context.Context, in *GetPinByParticipantRequest, opts ...grpc.CallOption) (*GetPinsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPinsResponse)
	err := c.cc.Invoke(ctx, PlansService_GetPinByParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) UpdatePin(ctx context.Context, in *UpdatePinRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, PlansService_UpdatePin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) UpdatePinImage(ctx context.Context, in *UpdatePinImageRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, PlansService_UpdatePinImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) DeletePinByID(ctx context.Context, in *PinIDRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, PlansService_DeletePinByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) DeletePinByWhiteboard(ctx context.Context, in *ManyPinIDRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, PlansService_DeletePinByWhiteboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) CreateWhiteboard(ctx context.Context, in *CreateWhiteboardRequest, opts ...grpc.CallOption) (*CreateWhiteboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWhiteboardResponse)
	err := c.cc.Invoke(ctx, PlansService_CreateWhiteboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) GetWhiteboardByID(ctx context.Context, in *WhiteboardIDRequest, opts ...grpc.CallOption) (*GetWhiteboardByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWhiteboardByIDResponse)
	err := c.cc.Invoke(ctx, PlansService_GetWhiteboardByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) UpdateWhiteboard(ctx context.Context, in *UpdateWhiteboardRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, PlansService_UpdateWhiteboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) DeleteWhiteboardByID(ctx context.Context, in *WhiteboardIDRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, PlansService_DeleteWhiteboardByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) CreateTrip(ctx context.Context, in *CreateTripRequest, opts ...grpc.CallOption) (*CreateTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTripResponse)
	err := c.cc.Invoke(ctx, PlansService_CreateTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) GetTripByID(ctx context.Context, in *TripIDRequest, opts ...grpc.CallOption) (*GetTripByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTripByIDResponse)
	err := c.cc.Invoke(ctx, PlansService_GetTripByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) UpdateTrip(ctx context.Context, in *UpdateTripRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, PlansService_UpdateTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) UpdateTripImage(ctx context.Context, in *UpdateTripImageRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, PlansService_UpdateTripImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) DeleteTripByID(ctx context.Context, in *TripIDRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, PlansService_DeleteTripByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlansServiceServer is the server API for PlansService service.
// All implementations must embed UnimplementedPlansServiceServer
// for forward compatibility.
type PlansServiceServer interface {
	// pin
	CreatePin(context.Context, *CreatePinRequest) (*CreatePinResponse, error)
	GetPinByID(context.Context, *PinIDRequest) (*GetPinByIDResponse, error)
	GetPinsByWhiteboard(context.Context, *ManyPinIDRequest) (*GetPinsResponse, error)
	GetPinByParticipant(context.Context, *GetPinByParticipantRequest) (*GetPinsResponse, error)
	UpdatePin(context.Context, *UpdatePinRequest) (*SuccessResponse, error)
	UpdatePinImage(context.Context, *UpdatePinImageRequest) (*SuccessResponse, error)
	DeletePinByID(context.Context, *PinIDRequest) (*SuccessResponse, error)
	DeletePinByWhiteboard(context.Context, *ManyPinIDRequest) (*SuccessResponse, error)
	// whiteboard
	CreateWhiteboard(context.Context, *CreateWhiteboardRequest) (*CreateWhiteboardResponse, error)
	GetWhiteboardByID(context.Context, *WhiteboardIDRequest) (*GetWhiteboardByIDResponse, error)
	UpdateWhiteboard(context.Context, *UpdateWhiteboardRequest) (*SuccessResponse, error)
	DeleteWhiteboardByID(context.Context, *WhiteboardIDRequest) (*SuccessResponse, error)
	// trip
	CreateTrip(context.Context, *CreateTripRequest) (*CreateTripResponse, error)
	GetTripByID(context.Context, *TripIDRequest) (*GetTripByIDResponse, error)
	UpdateTrip(context.Context, *UpdateTripRequest) (*SuccessResponse, error)
	UpdateTripImage(context.Context, *UpdateTripImageRequest) (*SuccessResponse, error)
	DeleteTripByID(context.Context, *TripIDRequest) (*SuccessResponse, error)
	mustEmbedUnimplementedPlansServiceServer()
}

// UnimplementedPlansServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlansServiceServer struct{}

func (UnimplementedPlansServiceServer) CreatePin(context.Context, *CreatePinRequest) (*CreatePinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePin not implemented")
}
func (UnimplementedPlansServiceServer) GetPinByID(context.Context, *PinIDRequest) (*GetPinByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPinByID not implemented")
}
func (UnimplementedPlansServiceServer) GetPinsByWhiteboard(context.Context, *ManyPinIDRequest) (*GetPinsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPinsByWhiteboard not implemented")
}
func (UnimplementedPlansServiceServer) GetPinByParticipant(context.Context, *GetPinByParticipantRequest) (*GetPinsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPinByParticipant not implemented")
}
func (UnimplementedPlansServiceServer) UpdatePin(context.Context, *UpdatePinRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePin not implemented")
}
func (UnimplementedPlansServiceServer) UpdatePinImage(context.Context, *UpdatePinImageRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePinImage not implemented")
}
func (UnimplementedPlansServiceServer) DeletePinByID(context.Context, *PinIDRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePinByID not implemented")
}
func (UnimplementedPlansServiceServer) DeletePinByWhiteboard(context.Context, *ManyPinIDRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePinByWhiteboard not implemented")
}
func (UnimplementedPlansServiceServer) CreateWhiteboard(context.Context, *CreateWhiteboardRequest) (*CreateWhiteboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWhiteboard not implemented")
}
func (UnimplementedPlansServiceServer) GetWhiteboardByID(context.Context, *WhiteboardIDRequest) (*GetWhiteboardByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWhiteboardByID not implemented")
}
func (UnimplementedPlansServiceServer) UpdateWhiteboard(context.Context, *UpdateWhiteboardRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWhiteboard not implemented")
}
func (UnimplementedPlansServiceServer) DeleteWhiteboardByID(context.Context, *WhiteboardIDRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWhiteboardByID not implemented")
}
func (UnimplementedPlansServiceServer) CreateTrip(context.Context, *CreateTripRequest) (*CreateTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrip not implemented")
}
func (UnimplementedPlansServiceServer) GetTripByID(context.Context, *TripIDRequest) (*GetTripByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTripByID not implemented")
}
func (UnimplementedPlansServiceServer) UpdateTrip(context.Context, *UpdateTripRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrip not implemented")
}
func (UnimplementedPlansServiceServer) UpdateTripImage(context.Context, *UpdateTripImageRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTripImage not implemented")
}
func (UnimplementedPlansServiceServer) DeleteTripByID(context.Context, *TripIDRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTripByID not implemented")
}
func (UnimplementedPlansServiceServer) mustEmbedUnimplementedPlansServiceServer() {}
func (UnimplementedPlansServiceServer) testEmbeddedByValue()                      {}

// UnsafePlansServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlansServiceServer will
// result in compilation errors.
type UnsafePlansServiceServer interface {
	mustEmbedUnimplementedPlansServiceServer()
}

func RegisterPlansServiceServer(s grpc.ServiceRegistrar, srv PlansServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlansServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlansService_ServiceDesc, srv)
}

func _PlansService_CreatePin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).CreatePin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_CreatePin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).CreatePin(ctx, req.(*CreatePinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_GetPinByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).GetPinByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_GetPinByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).GetPinByID(ctx, req.(*PinIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_GetPinsByWhiteboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManyPinIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).GetPinsByWhiteboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_GetPinsByWhiteboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).GetPinsByWhiteboard(ctx, req.(*ManyPinIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_GetPinByParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPinByParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).GetPinByParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_GetPinByParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).GetPinByParticipant(ctx, req.(*GetPinByParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_UpdatePin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).UpdatePin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_UpdatePin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).UpdatePin(ctx, req.(*UpdatePinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_UpdatePinImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePinImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).UpdatePinImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_UpdatePinImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).UpdatePinImage(ctx, req.(*UpdatePinImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_DeletePinByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).DeletePinByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_DeletePinByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).DeletePinByID(ctx, req.(*PinIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_DeletePinByWhiteboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManyPinIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).DeletePinByWhiteboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_DeletePinByWhiteboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).DeletePinByWhiteboard(ctx, req.(*ManyPinIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_CreateWhiteboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWhiteboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).CreateWhiteboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_CreateWhiteboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).CreateWhiteboard(ctx, req.(*CreateWhiteboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_GetWhiteboardByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhiteboardIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).GetWhiteboardByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_GetWhiteboardByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).GetWhiteboardByID(ctx, req.(*WhiteboardIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_UpdateWhiteboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWhiteboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).UpdateWhiteboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_UpdateWhiteboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).UpdateWhiteboard(ctx, req.(*UpdateWhiteboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_DeleteWhiteboardByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhiteboardIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).DeleteWhiteboardByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_DeleteWhiteboardByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).DeleteWhiteboardByID(ctx, req.(*WhiteboardIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_CreateTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).CreateTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_CreateTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).CreateTrip(ctx, req.(*CreateTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_GetTripByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TripIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).GetTripByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_GetTripByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).GetTripByID(ctx, req.(*TripIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_UpdateTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).UpdateTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_UpdateTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).UpdateTrip(ctx, req.(*UpdateTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_UpdateTripImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTripImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).UpdateTripImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_UpdateTripImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).UpdateTripImage(ctx, req.(*UpdateTripImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_DeleteTripByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TripIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).DeleteTripByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_DeleteTripByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).DeleteTripByID(ctx, req.(*TripIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlansService_ServiceDesc is the grpc.ServiceDesc for PlansService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlansService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plan.PlansService",
	HandlerType: (*PlansServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePin",
			Handler:    _PlansService_CreatePin_Handler,
		},
		{
			MethodName: "GetPinByID",
			Handler:    _PlansService_GetPinByID_Handler,
		},
		{
			MethodName: "GetPinsByWhiteboard",
			Handler:    _PlansService_GetPinsByWhiteboard_Handler,
		},
		{
			MethodName: "GetPinByParticipant",
			Handler:    _PlansService_GetPinByParticipant_Handler,
		},
		{
			MethodName: "UpdatePin",
			Handler:    _PlansService_UpdatePin_Handler,
		},
		{
			MethodName: "UpdatePinImage",
			Handler:    _PlansService_UpdatePinImage_Handler,
		},
		{
			MethodName: "DeletePinByID",
			Handler:    _PlansService_DeletePinByID_Handler,
		},
		{
			MethodName: "DeletePinByWhiteboard",
			Handler:    _PlansService_DeletePinByWhiteboard_Handler,
		},
		{
			MethodName: "CreateWhiteboard",
			Handler:    _PlansService_CreateWhiteboard_Handler,
		},
		{
			MethodName: "GetWhiteboardByID",
			Handler:    _PlansService_GetWhiteboardByID_Handler,
		},
		{
			MethodName: "UpdateWhiteboard",
			Handler:    _PlansService_UpdateWhiteboard_Handler,
		},
		{
			MethodName: "DeleteWhiteboardByID",
			Handler:    _PlansService_DeleteWhiteboardByID_Handler,
		},
		{
			MethodName: "CreateTrip",
			Handler:    _PlansService_CreateTrip_Handler,
		},
		{
			MethodName: "GetTripByID",
			Handler:    _PlansService_GetTripByID_Handler,
		},
		{
			MethodName: "UpdateTrip",
			Handler:    _PlansService_UpdateTrip_Handler,
		},
		{
			MethodName: "UpdateTripImage",
			Handler:    _PlansService_UpdateTripImage_Handler,
		},
		{
			MethodName: "DeleteTripByID",
			Handler:    _PlansService_DeleteTripByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plan.proto",
}
